image: "rikorose/gcc-cmake"

stages:
  - test
  - deploy

.test_template: &test_definition
  stage: test
  before_script:
    - cmake -H. -Bbuild
    - make -j8 -C build
  script:
    - ./build/unit_tests -s

test_master:
  <<: *test_definition
  only:
    refs:
      - master


pages:
  stage: deploy
  script:
  - mv docs/html/* public/
  artifacts:
    paths:
    - public
  only:
  - master
