image: "rikorose/gcc-cmake"

stages:
  - test

.test_template: &test_definition
  stage: test
  before_script:
    - cmake -H. -Bbuild
    - make -j8 -C build
  script:
    - ./build/unit_tests -s

test_master:
  <<: *test_definition
  only:
    refs:
      - master
